#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WoTB_APK_Editor.Resource", IsApplication=true)]

namespace WoTB_APK_Editor
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int APK_Tenkai_B = 2130903040;
			
			// aapt resource value: 0x7F030004
			public const int Backup_B = 2130903044;
			
			// aapt resource value: 0x7F030001
			public const int BGM_B = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int BGM_Exit_B = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int BGM_Select_B = 2130903043;
			
			// aapt resource value: 0x7F030005
			public const int Change_Sample_BGM_B = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int Change_Sample_Voice_B = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int Download_Progress = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int Kankore_B = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int Kankore_P = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int Sample_BGM_B = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int Sample_Voice_B = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int Select_BGM_File_B = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int Test_B = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int Wait_P = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int Wait_Text = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int Zip_Help_B = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int Zip_Select_B = 2130903057;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040001
			public const int activity_main = 2130968577;
			
			// aapt resource value: 0x7F040000
			public const int Music_Layout = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int Icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_foreground = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int ic_launcher_round = 2131034115;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F060000
			public const int ASMR_01 = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int ASMR_02 = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int ASMR_03 = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int ASMR_04 = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int ASMR_05 = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int Ayase_01 = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int Ayase_02 = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int Ayase_03 = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int Ayase_04 = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int Ayase_05 = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int Criss_01 = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int Criss_02 = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int Criss_03 = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int Criss_04 = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int Criss_05 = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int GuP_01 = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int GuP_02 = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int GuP_03 = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int GuP_04 = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int GuP_05 = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int Icon = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int Kankore_01 = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int Kankore_02 = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int Kankore_03 = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int Kankore_04 = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int Kankore_05 = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int Kankore_BGM_01 = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int Kankore_BGM_02 = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int Kankore_BGM_03 = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int Kankore_BGM_04 = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int Kankore_BGM_05 = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int Two_Steps_From_Hell_01 = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int Two_Steps_From_Hell_02 = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int Two_Steps_From_Hell_03 = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int Two_Steps_From_Hell_04 = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int Two_Steps_From_Hell_05 = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int Wiss_01 = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int Wiss_02 = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int Wiss_03 = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int Wiss_04 = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int Wiss_05 = 2131099688;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int action_settings = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int app_name = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F080000
			public const int AppTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
